title: Devon Birdseye, Ph.D. 
logo: "/images/devonHeadshot.png?raw=true" 
description: > 
  <br>
  <b>Computational Biologist</b>
  <br><br>
  With specialization in molecular biology, biochemistry, omics, statistical analysis and data visualization, I am passionate about empowering 
  research through compelling visuals and bridging the gap between data and discovery.
  <br><br>
  <a href="https://www.linkedin.com/in/devon-birdseye/">LinkedIn</a> 
  <br>
  <a href="https://scholar.google.com/citations?hl=en&user=oKiVX_sAAAAJ&view_op=list_works&sortby=pubdate">Google Scholar</a> 
  <br>
  <a href="https://orcid.org/0000-0003-1767-8486">ORCID</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-186709496-1 # your Google Analytics tracking ID here
