title: Devon Birdseye # your name (or website title) here
logo: "/images/devonHeadshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br><br>
  Bioinformatician 
  <br><br>
  Specializing in molecular biology, biochemistry, -omics, and data analysis/visualization in R and Python
  <br><br>
  <a href="https://www.linkedin.com/in/devon-birdseye/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://scholar.google.com/citations?hl=en&user=oKiVX_sAAAAJ&view_op=list_works&sortby=pubdate">View My Google Scholar Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-186709496-1 # your Google Analytics tracking ID here
