title: Devon Birdseye # your name (or website title) here
logo: "/images/devonHeadshot.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Computational Biologist / Bioinformatician 
  <br><br>
  Seven years of experience in molecular biology, biochemistry, -omics, and data analysis and visualization in R
  <br><br>
  <a href="https://www.linkedin.com/in/devon-birdseye/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-186709496-1 # your Google Analytics tracking ID here
