title: Devon Birdseye, Ph.D. 
logo: "/images/headshoot3.png?raw=true" 
description: > 
  <br>
  <b>Computational Biologist</b>
  <br><br>
  With specialization in molecular biology, biochemistry, omics, statistical analysis and data visualization, I am passionate about empowering 
  research through compelling visuals and bridging the gap between data and discovery.
  <br><br>
  <a href="/CurriculumVitae">Curriculum Vitae</a> 
  <br><br>
  <a href="https://github.com/devonbirdseye"target="_blank"><img src="/githublogo.png" style="width:60px;height:17px;"></a>
  &nbsp&nbsp&nbsp
  <a href="https://www.linkedin.com/in/devon-birdseye/"target="_blank"><img src="/linkedin.png" style="width:60px;height:17px;"></a>
  &nbsp&nbsp&nbsp
  <a href="https://orcid.org/0000-0003-1767-8486"target="_blank"><img src="/orcidlogo.png" style="width:50px;height:17px;"></a>
  
theme: jekyll-theme-minimal
google_analytics: UA-186709496-1 # your Google Analytics tracking ID here
